# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news_scraper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12news_scraper.proto\x12\x0cnews_scraper\"4\n\rScrapeRequest\x12\x14\n\x0cmax_articles\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\"\x87\x01\n\x0eScrapeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\'\n\x08\x61rticles\x18\x03 \x03(\x0b\x32\x15.news_scraper.Article\x12\x17\n\x0fprocessed_count\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"3\n\x12GetArticlesRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\"d\n\x13GetArticlesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\'\n\x08\x61rticles\x18\x02 \x03(\x0b\x32\x15.news_scraper.Article\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\xc7\x01\n\x07\x41rticle\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x16\n\x0epublished_date\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x11\n\timage_url\x18\x07 \x01(\t\x12&\n\x07summary\x18\x08 \x01(\x0b\x32\x15.news_scraper.Summary\x12\x0c\n\x04tags\x18\t \x03(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\"A\n\x07Summary\x12\x14\n\x0csummary_text\x18\x01 \x01(\t\x12\x12\n\nkey_points\x18\x02 \x03(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t2\xff\x01\n\x12NewsScraperService\x12K\n\x0eScrapeArticles\x12\x1b.news_scraper.ScrapeRequest\x1a\x1c.news_scraper.ScrapeResponse\x12R\n\x0bGetArticles\x12 .news_scraper.GetArticlesRequest\x1a!.news_scraper.GetArticlesResponse\x12H\n\x0bHealthCheck\x12\x1b.news_scraper.HealthRequest\x1a\x1c.news_scraper.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'news_scraper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCRAPEREQUEST']._serialized_start=36
  _globals['_SCRAPEREQUEST']._serialized_end=88
  _globals['_SCRAPERESPONSE']._serialized_start=91
  _globals['_SCRAPERESPONSE']._serialized_end=226
  _globals['_GETARTICLESREQUEST']._serialized_start=228
  _globals['_GETARTICLESREQUEST']._serialized_end=279
  _globals['_GETARTICLESRESPONSE']._serialized_start=281
  _globals['_GETARTICLESRESPONSE']._serialized_end=381
  _globals['_HEALTHREQUEST']._serialized_start=383
  _globals['_HEALTHREQUEST']._serialized_end=398
  _globals['_HEALTHRESPONSE']._serialized_start=400
  _globals['_HEALTHRESPONSE']._serialized_end=468
  _globals['_ARTICLE']._serialized_start=471
  _globals['_ARTICLE']._serialized_end=670
  _globals['_SUMMARY']._serialized_start=672
  _globals['_SUMMARY']._serialized_end=737
  _globals['_NEWSSCRAPERSERVICE']._serialized_start=740
  _globals['_NEWSSCRAPERSERVICE']._serialized_end=995
# @@protoc_insertion_point(module_scope)
