export const mockSkillsData = [
  // Current (2025) - Peak Performance
  {
    techStack: [
      { name: "Python", level: 90 },
      { name: "TypeScript", level: 85 },
      { name: "NestJS", level: 80 },
      { name: "Redis", level: 75 },
      { name: "Docker", level: 80 },
      { name: "MongoDB", level: 80 },
      { name: "PostgreSQL", level: 75 },
      { name: "WebSockets", level: 70 },
      { name: "GraphQL", level: 65 },
      { name: "gRPC", level: 60 },
      { name: "AWS", level: 80 },
    ],
    llmAgents: 80,
    react: 85,
    nextjs: 80,
    tailwind: 95,
    framer: 70,
    cicd: 70,
    hackathonWins: 3,
    projectsBuilt: 20,
    infraMaturity: 80,
  },
  // Nov 2024 - Third Hackathon Win
  {
    techStack: [
      { name: "Python", level: 85 },
      { name: "TypeScript", level: 80 },
      { name: "NestJS", level: 75 },
      { name: "Redis", level: 70 },
      { name: "Docker", level: 75 },
      { name: "MongoDB", level: 75 },
      { name: "PostgreSQL", level: 70 },
      { name: "WebSockets", level: 65 },
      { name: "GraphQL", level: 60 },
      { name: "gRPC", level: 55 },
      { name: "AWS", level: 75 },
    ],
    llmAgents: 75,
    react: 80,
    nextjs: 75,
    tailwind: 90,
    framer: 65,
    cicd: 65,
    hackathonWins: 3,
    projectsBuilt: 18,
    infraMaturity: 70,
  },
  // Oct 2024 - Second Hackathon Win
  {
    techStack: [
      { name: "Python", level: 80 },
      { name: "TypeScript", level: 75 },
      { name: "NestJS", level: 70 },
      { name: "Redis", level: 65 },
      { name: "Docker", level: 70 },
      { name: "MongoDB", level: 70 },
      { name: "PostgreSQL", level: 65 },
      { name: "WebSockets", level: 60 },
      { name: "GraphQL", level: 55 },
      { name: "gRPC", level: 50 },
      { name: "AWS", level: 70 },
    ],
    llmAgents: 70,
    react: 75,
    nextjs: 70,
    tailwind: 85,
    framer: 60,
    cicd: 60,
    hackathonWins: 2,
    projectsBuilt: 15,
    infraMaturity: 60,
  },
  // 2023-2024 - Growth Period
  {
    techStack: [
      { name: "Python", level: 70 },
      { name: "TypeScript", level: 65 },
      { name: "NestJS", level: 60 },
      { name: "Redis", level: 55 },
      { name: "Docker", level: 60 },
      { name: "MongoDB", level: 65 },
      { name: "PostgreSQL", level: 60 },
      { name: "WebSockets", level: 50 },
      { name: "GraphQL", level: 45 },
      { name: "gRPC", level: 40 },
      { name: "AWS", level: 60 },
    ],
    llmAgents: 60,
    react: 70,
    nextjs: 65,
    tailwind: 80,
    framer: 55,
    cicd: 50,
    hackathonWins: 1,
    projectsBuilt: 12,
    infraMaturity: 50,
  },
  // 2022 - First Hackathon Win
  {
    techStack: [
      { name: "Python", level: 60 },
      { name: "TypeScript", level: 55 },
      { name: "NestJS", level: 45 },
      { name: "Redis", level: 40 },
      { name: "Docker", level: 50 },
      { name: "MongoDB", level: 55 },
      { name: "PostgreSQL", level: 50 },
      { name: "WebSockets", level: 40 },
      { name: "GraphQL", level: 35 },
      { name: "gRPC", level: 30 },
      { name: "AWS", level: 50 },
    ],
    llmAgents: 45,
    react: 65,
    nextjs: 60,
    tailwind: 75,
    framer: 45,
    cicd: 40,
    hackathonWins: 1,
    projectsBuilt: 8,
    infraMaturity: 35,
  },
]
